"""MVP baseline including device credentials"""
from alembic import op
import sqlalchemy as sa

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('camera_model', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_external_id'), 'devices', ['external_id'], unique=True)
    op.create_table('security_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=True),
    sa.Column('credential_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_audit_occurred_at'), 'security_audit', ['occurred_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('detections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_color'), 'detections', ['color'], unique=False)
    op.create_index(op.f('ix_detections_device_id'), 'detections', ['device_id'], unique=False)
    op.create_index(op.f('ix_detections_observed_at'), 'detections', ['observed_at'], unique=False)
    op.create_index(op.f('ix_detections_vehicle_type'), 'detections', ['vehicle_type'], unique=False)
    op.create_table('device_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_credentials_device_id'), 'device_credentials', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_credentials_token_hash'), 'device_credentials', ['token_hash'], unique=True)
    op.create_table('device_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_device_id', sa.Uuid(), nullable=False),
    sa.Column('to_device_id', sa.Uuid(), nullable=False),
    sa.Column('road_distance_m', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['from_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['to_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_device_id', 'to_device_id', name='uq_device_link_pair')
    )
    op.create_table('ingested_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('node_version', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('model_version', sa.String(length=120), nullable=False),
    sa.Column('model_digest', sa.String(length=200), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detection_count', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'session_id', 'sequence_number', name='uq_ingest_sequence')
    )
    op.create_index(op.f('ix_ingested_events_device_id'), 'ingested_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_ingested_events_event_id'), 'ingested_events', ['event_id'], unique=True)
    op.create_table('queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=False),
    sa.Column('time_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edge_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('detection_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_event_id', sa.Uuid(), nullable=False),
    sa.Column('last_event_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detection_id'),
    sa.UniqueConstraint('device_id', 'session_id', 'track_id', 'first_seen', name='uq_edge_observation')
    )
    op.create_index(op.f('ix_edge_observations_device_id'), 'edge_observations', ['device_id'], unique=False)
    op.create_table('route_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('has_distant_gaps', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_results_query_id'), 'route_results', ['query_id'], unique=False)
    op.create_table('route_result_detections',
    sa.Column('route_result_id', sa.Uuid(), nullable=False),
    sa.Column('detection_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.ForeignKeyConstraint(['route_result_id'], ['route_results.id'], ),
    sa.PrimaryKeyConstraint('route_result_id', 'detection_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_result_detections')
    op.drop_index(op.f('ix_route_results_query_id'), table_name='route_results')
    op.drop_table('route_results')
    op.drop_index(op.f('ix_edge_observations_device_id'), table_name='edge_observations')
    op.drop_table('edge_observations')
    op.drop_table('queries')
    op.drop_index(op.f('ix_ingested_events_event_id'), table_name='ingested_events')
    op.drop_index(op.f('ix_ingested_events_device_id'), table_name='ingested_events')
    op.drop_table('ingested_events')
    op.drop_table('device_links')
    op.drop_index(op.f('ix_device_credentials_token_hash'), table_name='device_credentials')
    op.drop_index(op.f('ix_device_credentials_device_id'), table_name='device_credentials')
    op.drop_table('device_credentials')
    op.drop_index(op.f('ix_detections_vehicle_type'), table_name='detections')
    op.drop_index(op.f('ix_detections_observed_at'), table_name='detections')
    op.drop_index(op.f('ix_detections_device_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_color'), table_name='detections')
    op.drop_table('detections')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_audit_occurred_at'), table_name='security_audit')
    op.drop_table('security_audit')
    op.drop_index(op.f('ix_devices_external_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
